### ISSUE TITLE
VSIX Installer or Marketplace release?

### ISSUE THREAD

**Issue by TylerSeiford** [Mechanical-Advantage/EventDeployExtension#1]
After watching your great presentation on AdvantageKit, I found this repo for your event deploying, but I'm struggling to get it installed.

Would it be possible for you to release a VSIX installer or perhaps to the VSCode marketplace?

**Comment by jwbonner** [comment]
Published to the marketplace: https://marketplace.visualstudio.com/items?itemName=Mechanical-Advantage.event-deploy-wpilib

That was surprisingly easy to set up, thanks for the suggestion.
